name: flutter_practice
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# mac 2.16.2 #win 2.15.0
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.1"
  #flutter: ">=1.12.13+hotfix.5"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  sqflite: ^2.0.2
  path: ^1.8.0
  shared_preferences: ^2.0.13
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  dart_extensions: ^2.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  json_annotation: ^4.5.0
  fluttertoast: ^8.0.9
  after_layout: ^1.1.0
  event_bus: ^2.0.0
  rxdart: ^0.27.3
  flutter_local_notifications: ^9.5.3+1
  path_provider: ^2.0.10
  intl_utils: ^2.6.1
  #intl_generator: ^0.2.1
  flutter_native_timezone: ^2.0.0
  image: ^3.1.3
  device_info_plus: ^3.2.3
  flutter_swiper: ^1.1.6
  flutter_statusbar_manager : ^2.0.0
  webview_flutter: ^3.0.4
  flutterfire_ui: ^0.4.1
  firebase_auth: ^3.3.18
  firebase_database: ^9.0.14
  firebase_core: ^1.17.0
  firebase_core_web: ^1.6.4
  firebase_core_platform_interface: ^4.4.0
  firebase_analytics: ^9.1.8
  firebase_crashlytics: ^2.8.0
  firebase_app_check: ^0.0.6+12
  firebase_functions_dart: ^0.1.1+1
  firebase_functions_desktop: ^0.2.0+1
  firebase_admin: ^0.2.0-dev.7
  firebase_admin_sdk: ^0.0.1
  firebase_messaging: ^11.4.0
  firebase_messaging_web: ^2.4.0
  firebase_messaging_platform_interface: ^3.5.0
  firebase_storage: ^10.2.16
  #firebase_ml_vision: ^0.12.0+3
  google_ml_kit: ^0.11.0
  #firebase_cloud_messaging: ^4.0.4+1
  #tflite: ^1.1.2
  cloud_functions: ^3.2.15
  plugin_platform_interface: ^2.0.0
  image_picker: ^0.8.5+3
  camera: ^0.9.7
  video_player: ^2.4.2
  image_gallery_saver: ^1.7.1
  gallery_saver: ^2.3.2
  visibility_detector: ^0.2.2 #batter_player衝突
  open_app_settings: ^2.0.1
  permission_handler: ^9.2.0
  counter: ^0.2.2
  flutter_image_compress: ^1.1.0
  auto_orientation: ^2.2.1  #控制横竖屏控件
  screen: ^0.0.5            #控制屏幕亮度以及屏幕常亮组件 Embedded V2
  common_utils: ^2.1.0      #格式化时间日期组件
  battery: ^2.0.3
  battery_info: ^1.1.1
  battery_plus: ^2.1.3
  chewie: ^1.3.3
  agora_rtc_engine: ^5.2.0
  agora_rtm: ^1.1.1
  better_player: ^0.0.82
  #camera_with_rtmp: ^0.3.2
  dotted_border: ^2.0.0+2
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_easyloading: ^3.0.5
  fl_chart: ^0.51.0
  styled_widget: ^0.4.0+3
  qr_flutter: ^4.0.0 #QRcode
  expandable: ^5.0.1
  flutter_keyboard_visibility: ^5.2.0
  google_fonts: ^3.0.1
  animations: ^2.0.3
  animate_do: ^2.1.0
  animated_text_kit: ^4.1.0
  get: ^4.6.5
  #flutter_riverpod: ^0.12.4
  web_socket_channel: ^2.2.0 #Server溝通
  mqtt_client: ^9.6.8
  dartx: ^1.1.0
  uuid: ^3.0.6
  statsfl: ^2.3.0
  encrypt: ^5.0.1
  cached_network_image: ^3.0.0
  flutter_svg: ^1.0.0
  get_storage: ^2.0.3 #SharedPeference
  flutter_cache_manager: ^3.3.0
  photo_view: ^0.14.0
  octo_image: ^1.0.2
  universal_platform: ^1.0.0+1
  flutter_screenutil: ^5.5.3+2
  timeago: ^3.2.2
  file_picker: ^4.6.1
  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.1.3
  time: ^2.1.1
  flutter_colorpicker: ^1.0.3
  ble: ^2.0.0
  flutter_blue_elves: ^0.1.9
  #flutter_blue: ^0.8.0 #dart衝突
  #flutter_ble_lib: ^2.3.2
  #flutter_reactive_ble: ^5.0.2
  #flutter_control: ^2.5.1+3
  #flutter_xupdate: ^2.0.2 #功能集成
  #flutter_app_upgrade: ^1.1.0 #升級內容
  provider: ^6.0.3
  package_info_plus: ^1.4.2 #app詳細
  dart_ipify: ^1.1.1 #ipv4-v64
  flutter_widget_from_html: ^0.8.5 #html編輯器
  flutter_widget_from_html_core: ^0.8.5+3
  money2: ^2.3.0 #貨幣金額解析
  image_cropper: ^2.0.3 #切圖

dev_dependencies:
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  json_model: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - images/
    - assets/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add images to your application, add an images section, like this:
  # images:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding images from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true